name: "Run flask App CI/CD Pipeline with Docker Hub and GitHub Actions"
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Push Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-flask-app:${{github.run_number}} .

      - name : Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-flask-app:${{github.run_number}}

      - name: Run Docker Image
        run: docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/ms-flask-app:${{github.run_number}}

      # - name: Test Docker Image
      #   run: curl http://localhost:5000

      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.8
      # - name: Install requirements
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Running flask app
      #   run: python app.py

# YAML data
